api/urls.py
from django.urls import path

from payment.models import Account
from . import views
from api.views import *
from django.conf import settings
from django.conf.urls.static import static

# from rest_framework_simplejwt.views import (
#     TokenObtainPairView,
#     TokenRefreshView,
# )

urlpatterns = [
    # path("student", StudentApi.as_view()),
    path("student/<uid>", StudentApi.as_view()),
    path("student", StudentApi.as_view(), name="student"),
    path("", views.index, name="index"),

    path("driver/login", DriverApi.as_view()),
    path("driver/logout", DriverApi.as_view(), name="driver-shuttle"),
    path("driver/shuttle", DriverShuttleApi.as_view(), name="driver-shuttle"),    
    path("organization", OrganizationApi.as_view(), name="organization"),
    path("account", AccountApi.as_view(), name="payment"),

    # Voucher api
    path("voucher/is_available", VoucherApi.as_view(), name="voucher"),

]


urlpatterns = urlpatterns + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

authentication/urls.py
from os import name
from django.urls import path
from . import views

app_name = "authentication"
urlpatterns = [
    path("", view=views.index, name="index"),
    path("login/", view=views.login, name="login"),
    path("login-submit/", view=views.login_submit, name="login-submit"),
    path("logout/", view=views.logout, name="logout"),
]

dashboard/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from dashboard import views
from django.urls import path, include


app_name = "dashboard"
urlpatterns = [
    path("", view=views.index, name="index"),
    path("settings/", view=views.setting, name="settings"),
    path("update-organization/", view=views.update_organization, name="update-organization"),
    path("add-department/", view=views.add_department, name="add-department"),
    
    
]

urlpatterns = urlpatterns + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404

handler404 = 'authentication.views.error_404_handler'

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("landing.urls")),
    path("dashboard/authentication/", include("authentication.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("dashboard/vouchers/", include("vouchers.urls")),
    path("dashboard/students/", include("students.urls")),
    path("dashboard/drivers/", include("drivers.urls")),
    path("dashboard/shuttles/", include("shuttles.urls")),
    path("dashboard/map/", include("map.urls")),
    path("api/", include("api.urls")),
    path("", include("payment.urls")),
]

urlpatterns = urlpatterns + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)


admin.site.site_header = "Point Pay"
admin.site.site_title = "Point Pay Superadmin"
admin.site.index_title = "Welcome to superadmin portal"

dashboard/models.py
from email.policy import default
from statistics import mode
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from random import randint
from itertools import chain
import qrcode
import datetime

# Create your models here.

# python manage.py makemigrations
# python manage.py migrate
# python manage.py runserver

class Organization(models.Model):
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=15, default="organization")
    abbr = models.CharField(max_length=10, null=True)
    city = models.CharField(max_length=15)
    logo = models.ImageField(upload_to="logo")
    point_fee = models.FloatField(default=500)
    founded_in = models.DateField()
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)
    added_at = models.DateTimeField(default=timezone.now)

    def getJson(self):
        opts = self._meta
        opts.image_field
        data = {}
        for f in chain(opts.concrete_fields, opts.private_fields):
            print(f)
            data[f.name] = f.value_from_object(self)
        for f in opts.many_to_many:
            data[f.name] = [i.id for i in f.value_from_object(self)]
        return data
        # return model_to_dict(self)

    def makeAbbr(self, name):
        name_list_form = name.split(" ")
        abbr = ""
        for single_word in name_list_form:
            abbr += single_word[0].upper()
        return abbr

    def save(self, *args, **kwargs):
        if not self.pk and not self.abbr:
            self.abbr = self.MakeAbbr(self.name)
        super(Organization, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.name} ({self.abbr}) {self.city}"


class Department(models.Model):
    abbr = models.CharField(max_length=6)
    name = models.CharField(max_length=50)
    added_at = models.DateTimeField(default=timezone.now)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    
    def __str__(self) -> str:
        return f"{self.name} ({self.abbr})"

    def save(self, *args, **kwargs):
        self.abbr = self.abbr.upper()
        if not Department.objects.filter(organization = self.organization, abbr = self.abbr).exists():
            super(Department, self).save(*args, **kwargs)



class UserInfo(models.Model):
    uid = models.CharField(
        max_length=255,
        unique=True,
        null=True,
        blank=True,
        error_messages={"unique": "User with this UID number already exists."},
    )
    STATUS_CHOICES = [("student", "Student"), ("admin", "Admin")]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    stripe_cust_id = models.CharField(max_length=255, null = True, blank = True)
    roll_no = models.CharField(max_length=255, null=True, blank=True)
    profile_picture = models.ImageField(upload_to="dp", default="dp/profile.jpg")
    id_card_front_pic = models.ImageField(upload_to = "id-cards", null=True, blank = True)
    id_card_back_pic = models.ImageField(upload_to = "id-cards", null=True, blank = True)
    phone = models.CharField(
        max_length=17,
        unique=True,
        null=True,
        blank=True,
        error_messages={"unique": "User with this phone number already exists."},
    )
    status = models.CharField(choices=STATUS_CHOICES, max_length=255)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    added_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ("-added_at",)

    def validate_roll_no(self):
        if not self.roll_no:
            raise Exception("Roll no. is required")
        if "-" not in self.roll_no:
            raise Exception("Roll no. must be in correct format (CS-11001)")        
        print("given roll:", self.roll_no)
        all_dept_abbrs = Department.objects.filter(organization_id = self.organization_id).values_list("abbr", flat=True)
        print("all dept list: ", all_dept_abbrs)
        roll_splited = self.roll_no.split("-")
        print("=splitted roll no.", roll_splited)
        dept_part = roll_splited[0].upper()
        print("=dept part", dept_part)
        num_part = roll_splited[1]
        print("=number part", num_part)
        if dept_part not in all_dept_abbrs:
            raise Exception("Given department is not included in your university")
        if len(num_part) != 5:
            raise Exception("Roll no. must be in correct format (CS-11001)")
        current_timezone_year = timezone.now().year - 2000
        year_part = int(num_part[:2])
        number_part = int(num_part[2:])
        print("==year part", year_part, "<=>", "current year", current_timezone_year)
        print("==Seat part", number_part)
        
        if year_part > current_timezone_year:
            raise Exception("Given batch no. is invalid")

        if number_part > 300:
            raise Exception("Given seat no. is invalid")

        check_duplicate = UserInfo.objects.filter(roll_no = self.roll_no, organization_id = self.organization.id)
        if check_duplicate.exists():
            raise Exception("This roll no. is already in use.")

        return True        


        

    class Meta:
        verbose_name = "User"

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name} - {self.status} - {self.organization.abbr}"

    def save(self, *args, **kwargs):
        if self.pk and not self.roll_no and self.status == "student":
            self.validate_roll_no()
    
        
        if not self.pk and self.status == "student":
            self.validate_roll_no()
            # if not self.id_card_front_pic or not self.id_card_back_pic:
            #     raise Exception("ID card pictures are required.")

        phone = self.phone
        if phone:
            phone = phone.replace("-", "")
            phone = phone.replace("+", "")
            if not (phone.isnumeric() and (9 < len(phone) < 17)):
                raise Exception("Given phone number is not valid")

        super(UserInfo, self).save(*args, **kwargs)

    def getJson(self):
        student_info = {
            "id": self.pk,
            "first_name": self.user.first_name,
            "last_name": self.user.last_name,
            "email": self.user.email,
            "full_name": f"{self.user.first_name} {self.user.last_name}",
            "profile_picture": str(self.profile_picture),
        }
        return student_info

    def isVoucherAlreadyCreated(self):
        current_date = timezone.now()
        check_voucher_query = Voucher.objects.filter(
            organization=self.organization,
            month=current_date.month,
            year=current_date.year,
        ).order_by("-created_at")
        if check_voucher_query.exists():
            # returning last recent voucher
            return check_voucher_query[0]
        else:
            return False


class Voucher(models.Model):
    price = models.FloatField()
    code = models.CharField(max_length=255, null=True)
    month = models.IntegerField(default=1)
    year = models.IntegerField()
    qr_code_picture = models.ImageField(upload_to="qr", null=True)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    created_by = models.ForeignKey(UserInfo, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    is_expired = models.BooleanField(default=False)

    def __str__(self):
        month = datetime.date(1900, self.month, 1).strftime("%b")
        return f"{month} {self.year} - Rs.{self.price} - Expired: {self.is_expired}"

    def dateDict(self):
        return {
            "MONTH": datetime.date(1900, self.month, 1).strftime("%B"),
            "month": datetime.date(1900, self.month, 1).strftime("%b"),
            "year": self.year,
        }

    def showDate(self):
        month = datetime.date(1900, self.month, 1).strftime("%b")
        return f"{month}, {self.year}"

    def expireIt(self):
        # get current month and year
        current_date = timezone.now()
        month = current_date.month
        year = current_date.year
        if (self.year <= year) and self.month < month:
            self.is_expired = True
            self.save()

    def generateCode(self):
        length = 64
        """
        This function will return a string of random
        alphanumeric code of given length (integer)
        """
        CHAR = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
        code = ""
        for i in range(0, length):
            index = randint(0, len(CHAR) - 1)
            code += CHAR[index]
        return code

    def generate_qrcode(self):
        import time
        from io import BytesIO
        from django.core.files import File
        from PIL import Image, ImageDraw, ImageOps
        from django.conf import settings
        import os

        base_path = settings.BASE_DIR

        logo_path = os.path.join(base_path, "media", str(self.organization.logo))

        logo2 = Image.open(logo_path).convert("RGBA")
        # logo2.convert("1")
        # logo2 = self.add_corners(logo2, 100)
        # logo2 = ImageOps.grayscale(logo2)

        logo = Image.new("RGBA", logo2.size, "WHITE")
        logo.paste(logo2, mask=logo2)

        # taking base width
        basewidth = 120

        # adjust image size
        wpercent = basewidth / float(logo.size[0])
        hsize = int((float(logo.size[1]) * float(wpercent)))
        logo = logo.resize((basewidth, hsize), Image.ANTIALIAS)

        # return None
        qrcode_image = qrcode.make(self.code)

        # qrcode_image = qrcode_image.convert('RGB')

        pos = (
            (qrcode_image.size[0] - logo.size[0]) // 2,
            (qrcode_image.size[1] - logo.size[1]) // 2,
        )

        qrcode_image.paste(logo, pos)

        qrcode_image.save(os.path.join(base_path, "media", "practise.png"))

        canvas = Image.new(

dashboard/views.py
from django.contrib.auth.decorators import login_required
from dashboard.supporting_func import *
from dashboard.models import *
from django.shortcuts import render, redirect
from authentication.decorators import djangoAdminNotAllowed
from django.contrib import messages
from django.db import transaction

@djangoAdminNotAllowed
@login_required
def index(request):
    user = getUser(request.user)
    my_datetime = timezone.now().strftime("%B, %Y")
    context = {"page": "dashboard", "total_students": 1500, "timestamp": my_datetime}
    is_voucher_created = isVoucherAlreadyCreated(user)
    context["is_voucher_created"] = is_voucher_created
    return render(request, "home/dashboard.html", context)


@djangoAdminNotAllowed
@login_required
def setting(request):
    user = getUser(request.user)
    all_department = Department.objects.filter(organization = user.organization)
    print(all_department)
    context = {
        "page": "settings",
        "all_departments":  all_department,
    }
    return render(request, "home/settings.html", context)

@djangoAdminNotAllowed
@login_required
def update_organization(request):
    user = getUser(request.user)
    organization = user.organization
    if request.method == "POST":
        logo = request.FILES.get("logo")
        Type = request.POST.get("type")
        city = request.POST.get("city")
        fee = request.POST.get("fee")

        if logo:
            organization.logo = logo
        if Type != organization.type:
            organization.type = Type
        if city != organization.city:
            organization.city = city
        if fee != organization.point_fee:
            organization.point_fee = fee
        organization.save()
        messages.success(request, "Information has been updated")
        print(request.POST, request.FILES)

    return redirect("dashboard:settings")


@djangoAdminNotAllowed
@login_required
def add_department(request):
    user = getUser(request.user)
    if request.method == "POST":
        departments = request.POST.get("departments")
        if not departments:
            messages.error(request, "Departments required")
            return redirect("dashboard:settings")
        all_departments = departments.split("\n")
        
        try:
            with transaction.atomic():
                for department in all_departments:
                    each_dept = department.split(",")
                    abbr = each_dept[0]
                    name = each_dept[1]
                    Department.objects.create(
                        abbr=abbr, 
                        name=name, 
                        organization=user.organization)
            messages.success(request, "Departments have been added successfully!")
        except Exception as e:
            messages.error(request, "Incorrect format given in input field")

    return redirect("dashboard:settings")

templates/dashboard/includes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Point Pay - {% block title %}{% endblock title %}</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'dashboard/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'dashboard/css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link href="{% static 'all/css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'all/css/horizontal-view.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">


</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        {% include 'dashboard/includes/sidebar.html' %}
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="bg-white d-flex flex-column">

            <!-- Main Content -->
            <div id="content"  style="background-color: aliceblue;">

                <!-- Topbar -->
                {% include 'dashboard/includes/topbar.html' %}
                <!-- End of Topbar -->


                <!-- Begin Page Content -->
                {% block content %} {% endblock content %}
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{% url 'authentication:logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'dashboard/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'dashboard/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- For Downloading HTML to PDF -->
    <script src="https://raw.githack.com/eKoopmans/html2pdf/master/dist/html2pdf.bundle.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'dashboard/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'dashboard/js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'dashboard/vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'dashboard/js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'dashboard/js/demo/chart-pie-demo.js' %}"></script>
    <script src="{% static 'dashboard/js/spinner.js' %}"></script>    

    <!-- script to download -->
    <script src="{% static 'dashboard/js/admin/script.js' %}"></script>    
    
    <script>
        $(document).ready(function(){
          $('[data-toggle="tooltip"]').tooltip();   
        });
    </script>

</body>

</html>

templates/dashboard/includes/sidebar.html
{% load static %}

<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'dashboard:index' %}">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-credit-card"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Point pay</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <div class="bg-white m-3  text-center radius-10 p-3">
        
        <h4 class="my-0">{{ date.date }}</h4>
    </div>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <!-- <li class="nav-item active">
        <a class="nav-link" href="index.html">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li> -->

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <!-- <div class="sidebar-heading">
        Interface
    </div> -->

    <!-- Nav Item - Pages Collapse Menu -->
    <!-- <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Components</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Components:</h6>
                <a class="collapse-item" href="buttons.html">Buttons</a>
                <a class="collapse-item" href="cards.html">Cards</a>
            </div>
        </div>
    </li> -->

    <!-- Nav Item - Utilities Collapse Menu -->
    <!-- <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Utilities</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Utilities:</h6>
                <a class="collapse-item" href="utilities-color.html">Colors</a>
                <a class="collapse-item" href="utilities-border.html">Borders</a>
                <a class="collapse-item" href="utilities-animation.html">Animations</a>
                <a class="collapse-item" href="utilities-other.html">Other</a>
            </div>
        </div>
    </li> -->

    <!-- Divider -->
    <!-- <hr class="sidebar-divider"> -->

    <!-- Heading -->
    <!-- <div class="sidebar-heading">
        Pages
    </div> -->

    {% if not user_info.isVoucherAlreadyCreated %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:dashboard' user_info.organization.abbr user_info.status.name %}">
            <i class="fa fa-plus"></i>
            <span>
                Create QR code 
                &nbsp;
               <div class="spinner-grow spinner-grow-sm text-white mr-3"></div>
            </span>
        </a>
    </li>
    {% endif %}

    <!-- Nav Item - Charts -->
    {% for page in side_bar_pages %}
        {% if page.is_show_on_sidebar %}
            <li class="nav-item {% if page.url_name == current_section %}active{% endif %}">
                <a class="nav-link" href="
                    {% if page.url_name %}
                        {% url 'dashboard:dashboard' user_info.organization.abbr user_info.status.name page.url_name %}
                    {% else %}
                        {% url 'dashboard:dashboard' user_info.organization.abbr user_info.status.name %}
                    {% endif %}">
                    <i class="{{ page.icon }}"></i>
                    <span>{{ page.title }}</span>
                </a>
            </li>
        {% endif %}
    {% endfor %}

    <!-- Nav Item - Pages Collapse Menu -->
    <!-- <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
            aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Login Screens:</h6>
                <a class="collapse-item" href="login.html">Login</a>
                <a class="collapse-item" href="register.html">Register</a>
                <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="404.html">404 Page</a>
                <a class="collapse-item" href="blank.html">Blank Page</a>
            </div>
        </div>
    </li> -->

    <!-- Nav Item - Charts -->
    <!-- <li class="nav-item">
        <a class="nav-link" href="charts.html">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Charts</span></a>
    </li> -->

    <!-- Nav Item - Tables -->
    <!-- <li class="nav-item">
        <a class="nav-link" href="tables.html">
            <i class="fas fa-fw fa-table"></i>
            <span>Tables</span></a>
    </li> -->

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

    <!-- Sidebar Message -->
    <!-- <div class="sidebar-card d-none d-lg-flex">
        <img class="sidebar-card-illustration mb-2" src="{% static 'dashboard/img/undraw_rocket.svg' %}" alt="...">
        <p class="text-center mb-2"><strong>SB Admin Pro</strong> is packed with premium features, components, and more!</p>
        <a class="btn btn-success btn-sm" href="https://startbootstrap.com/theme/sb-admin-pro">Upgrade to Pro!</a>
    </div> -->

</ul>
<!-- End of Sidebar -->

templates/dashboard/includes/spinner.html
<div class="text-center py-5" id="spinner">
    <div class="spinner-border text-primary text-center" role="status">
        <span class="sr-only">Loading...</span>
    </div>    
</div>