api/urls.py
from django.urls import path

from payment.models import Account
from . import views
from api.views import *
from django.conf import settings
from django.conf.urls.static import static

# from rest_framework_simplejwt.views import (
#     TokenObtainPairView,
#     TokenRefreshView,
# )

urlpatterns = [
    # path("student", StudentApi.as_view()),
    path("student/<uid>", StudentApi.as_view()),
    path("student", StudentApi.as_view(), name="student"),
    path("", views.index, name="index"),

    path("driver/login", DriverApi.as_view()),
    path("driver/logout", DriverApi.as_view(), name="driver-shuttle"),
    path("driver/shuttle", DriverShuttleApi.as_view(), name="driver-shuttle"),    
    path("organization", OrganizationApi.as_view(), name="organization"),
    path("account", AccountApi.as_view(), name="payment"),

    # Voucher api
    path("voucher/is_available", VoucherApi.as_view(), name="voucher"),

]


urlpatterns = urlpatterns + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

shuttles/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.urls import path, include
from django.contrib.auth.decorators import login_required


app_name = "shuttles"
urlpatterns = [
    path("", login_required(views.ShuttleDetailView.as_view()), name="all"),
    path(
        "<pk>/view",
        login_required(views.ShuttleDetailView.as_view()),
        name="select-shuttle",
    ),
    path("<shuttle_id>/edit/", view=views.edit_shuttle, name="edit-shuttle"),
    path("add/", view=views.add_shuttle, name="add-shuttle"),
    path("<shuttle_id>/delete/", view=views.delete_shuttle, name="delete-shuttle"),
]

urlpatterns = urlpatterns + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404

handler404 = 'authentication.views.error_404_handler'

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("landing.urls")),
    path("dashboard/authentication/", include("authentication.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("dashboard/vouchers/", include("vouchers.urls")),
    path("dashboard/students/", include("students.urls")),
    path("dashboard/drivers/", include("drivers.urls")),
    path("dashboard/shuttles/", include("shuttles.urls")),
    path("dashboard/map/", include("map.urls")),
    path("api/", include("api.urls")),
    path("", include("payment.urls")),
]

urlpatterns = urlpatterns + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)


admin.site.site_header = "Point Pay"
admin.site.site_title = "Point Pay Superadmin"
admin.site.index_title = "Welcome to superadmin portal"

shuttles/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from dashboard.models import Organization
from django.utils import timezone
import uuid

# python manage.py makemigrations
# python manage.py migrate
# python manage.py runserver

# Create your models here.
class Shuttle(models.Model):
    id_number = models.IntegerField(default=0)
    shuttle_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    vehicle_number = models.CharField(validators=[MinLengthValidator(4)], max_length=10)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    is_running = models.BooleanField(default=False)
    added_at = models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
        if not self.pk:
            all_shuttles = Shuttle.objects.filter(
                organization=self.organization
            ).count()
            self.id_number = all_shuttles + 1
        super(Shuttle, self).save(*args, **kwargs)

    class Meta:
        ordering = ("id",)

    def __str__(self):
        return f"{self.vehicle_number} - {self.shuttle_id} - {self.id_number}"

shuttles/forms.py
from django.forms import ModelForm
from shuttles.models import *


class ShuttleForm(ModelForm):
    class Meta:
        model = Shuttle
        fields = "__all__"
        exclude = ["organization", "id_number", "added_at"]

shuttles/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from dashboard.supporting_func import *
from shuttles.models import Shuttle
from dashboard.supporting_func import getUser
from django.contrib import messages
from shuttles.forms import *
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from authentication.decorators import djangoAdminNotAllowed



class ShuttleListView(ListView):
    template_name = "home/shuttles/all-shuttles.html"
    model = Shuttle
    context_object_name = "all_shuttles"
    page = "shuttles"
    single_shuttle = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page"] = "shuttles"
        return context



class ShuttleDetailView(DetailView):
    model = Shuttle
    form_class = ShuttleForm
    context_object_name = "single_shuttle"
    template_name = "home/shuttles/all-shuttles.html"
    page = "shuttles"
    temp_obj = True

    def get_object(self):
        queryset = self.get_queryset()
        shuttle_id = self.kwargs.get("pk")
        if not shuttle_id:
            return None
        shuttle = queryset.filter(id=shuttle_id).first()
        if not shuttle:
            messages.error(
                self.request,
                "Shuttle doesn't exist with this id OR you don't have access",
            )
            self.temp_obj = False
        return shuttle

    def get_queryset(self):
        user = getUser(self.request.user)
        return self.model.objects.filter(organization=user.organization)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context["all_shuttles"] = self.get_queryset()
        context["page"] = "shuttles"
        return context

    def get(self, request, *args, **kwargs):
        if request.user.is_superuser:
            messages.error(request, "You are not allowed to access staff panel.")
            return redirect("authentication:logout")

        obj = self.get_object()
        if not self.temp_obj:
            return redirect("shuttles:all")
        return super(ShuttleDetailView, self).get(request, args, kwargs)


def get_pre_context(organization, form_title, shuttle_id):
    queryset = Shuttle.objects.filter(organization=organization)
    shuttle = queryset.filter(id=shuttle_id).first() if shuttle_id else None
    return {
        "page": "shuttles",
        "all_shuttles": queryset,
        "shuttle": shuttle,
        "form_title": form_title,
    }

@djangoAdminNotAllowed
@login_required
def edit_shuttle(request, shuttle_id):
    if not shuttle_id.isdigit():
        messages.error(request, "Given shuttle id is invalid")
        return redirect("shuttles:all")
    user = getUser(request.user)
    context = get_pre_context(user.organization, "Update shuttle details", shuttle_id)
    shuttle = context["shuttle"]
    if shuttle:
        if request.method == "POST":
            shuttle_form = ShuttleForm(request.POST, instance=shuttle)
            if shuttle_form.is_valid():
                shuttle_form.save()
                messages.success(
                    request, "Shuttle details has been updated successfully!"
                )
                return redirect("shuttles:select-shuttle", pk=shuttle.id)
        else:
            shuttle_form = ShuttleForm(instance=shuttle)
        context["shuttle_form"] = shuttle_form
        return render(request, "home/shuttles/all-shuttles.html", context)
    else:
        messages.error(
            request, "Shuttle doesn't exist with this id OR you don't have access"
        )
        return redirect("shuttles:all")

@djangoAdminNotAllowed
@login_required
def add_shuttle(request):
    user = getUser(request.user)
    context = get_pre_context(user.organization, "Add new shuttle", None)
    if request.method == "POST":
        shuttle_form = ShuttleForm(request.POST)
        if shuttle_form.is_valid():
            data = shuttle_form.cleaned_data
            new_shuttle = Shuttle(organization=user.organization, **data)
            new_shuttle.save()
            messages.success(request, "Shuttle has been added successfully")
            return redirect("shuttles:all")
    else:
        shuttle_form = ShuttleForm()
    context["shuttle_form"] = shuttle_form
    return render(request, "home/shuttles/all-shuttles.html", context)

@djangoAdminNotAllowed
@login_required
def delete_shuttle(request, shuttle_id):
    if not shuttle_id.isdigit():
        messages.error(request, "Given shuttle id is invalid")
        return redirect("shuttles:all")
    user = getUser(request.user)
    context = get_pre_context(user.organization, "Add new shuttle", shuttle_id)
    if context["shuttle"]:
        context["shuttle"].delete()
        messages.success(request, "Shuttle has been deleted successfully!")
    return redirect("shuttles:all")

templates/home/shuttles/all-shuttles.html
{% extends "layouts/base.html" %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}


{% load static %}

{% block title %} Dashboard {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row mb-2 mt-4">
    <div class="col-sm-8 d-flex align-items-center">
        <h1 class="fw-extrabold mb-0">Shuttles</h1>
    </div>

    <div class="col-sm-4 d-flex justify-content-end align-items-center">
        <a href="{% url 'shuttles:add-shuttle' %}">
            <button style="height: fit-content;" class="btn btn-gray-800 d-inline-flex align-items-center me-2 dropdown-toggle">
                <svg class="icon icon-xs me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
                Add New Shuttle
            </button>
        </a>
    </div>
</div>

<div class="row mt-3">
    <div class="col-sm-8">
        
        <div class="row">
            {% for shuttle in all_shuttles %}
            
            <div class="col-12 col-sm-6 col-xl-6 mb-4">
                <div class="card border-0 shadow">
                    <div class="card-body">
                        <div class="row d-block d-xl-flex align-items-center">
                            <div
                                class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
                                <!-- <div class="icon-shape icon-shape-primary rounded me-4 me-sm-0"> -->
                                <!-- <svg class="icon" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                            <path
                                                d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z">
                                            </path>
                                        </svg> -->

                                <!-- </div> -->
                                <div class="p-2">
                                    <a href="{% url 'shuttles:select-shuttle' shuttle.id %}">
                                        <img src="{% static 'bus1.png' %}" style="width: 100px; height: 100px;" class="" alt="">
                                    </a>
                                </div>
                                <div class="d-sm-none">
                                    <h2 class="h5">{{ shuttle.full_name }}</h2>
                                    <h3 class="fw-extrabold mb-1">ID # {{ shuttle.id_number }}</h3>
                                </div>
                            </div>
                            <div class="col-12 col-xl-7 px-xl-0">
                                <div class="d-none d-sm-block">
                                    <h2 class="h6 text-gray-400 mb-0">{{ shuttle.full_name }}</h2>
                                    <h3 class="fw-extrabold mb-1">ID # {{ shuttle.id_number }}</h3>
                                </div>
                                <small class="d-flex align-items-center text-gray-500">
                                    Vehicle # &nbsp; <b>{{ shuttle.vehicle_number }}</b>

                                </small>
                                <div class="small d-flex mt-1">
                                    <a href="{% url 'shuttles:edit-shuttle' shuttle.id %}">
                                        <button type="button" name="" id="" class="btn btn-outline-primary btn-block">Edit</button>
                                    </a>
                                    <a href="{% url 'shuttles:delete-shuttle' shuttle.id %}" onclick="return confirm('Are you sure you want to delete this shuttle?')">
                                        <button type="button" name="" id="" class="btn btn-outline-danger mx-2 btn-block">Delete</button>                                        
                                    </a>
                                    <!-- <div>Since last month <svg class="icon icon-xs text-success" fill="currentColor"
                                                viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                                <path fill-rule="evenodd"
                                                    d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z"
                                                    clip-rule="evenodd"></path>
                                            </svg>
                                            <span class="text-success fw-bolder">22%</span>
                                        </div> -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            
        </div>

    </div>

    <div class="col-sm-4 pb-4">
        <div class="card border-0 shadow">
            {% if shuttle_form %}
                <div class="card-body p-4">
                
                    <h3 class="fw-extrabold mb-3">{{ form_title }}</h3>
                    <form action="" enctype="multipart/form-data" method="post">
                        {% csrf_token %}
                        {% bootstrap_form shuttle_form layout="floating" %}
                        <div class="d-grid gap-2">
                            <button class="btn btn-primary btn-lg" type="submit">Save shuttle</button>
                        </div>
                    </form>
                </div>

            {% else %}
                {% if single_shuttle %}
                        <div class="card-header d-flex flex-row align-items-center flex-0 border-bottom">
                            <div class="d-block">
                                <div class="h6 fw-normal text-gray mb-2">Shuttle summary</div>
                        
                            </div>
                            <div class="d-block ms-auto">
                                <h2 class="h2 fw-extrabold mb-0">ID # {{ single_shuttle.id_number }}</h2>
                            </div>
                        
                        </div>
                        
                        <div class="card-body p-2">
                            <div>
                                <div class="text-center mt-4">
                                    <img style="width: 150px; height: 150px;"
                                        src="{% static 'bus1.png' %}" alt="">
                                </div>
                                <div class="p-4 py-0 pt-4">
                                    <div class="text-center">
                                        <h4 class="card-title my-0">{{ single_shuttle.full_name }}
                                        </h4>
                                    </div>
                        
                                </div>
                                <hr>
                                <div class="px-4 py-0 pb-4 pt-2">
                                    <div class="row mb-3">
                                        <div class="col-sm-4"><b>Vehicle no.</b></div>
                                        <div class="col-sm-8">{{ single_shuttle.vehicle_number }}</div>
                                    </div>
                                    <!-- <div class="row mb-3">
                                        <div class="col-sm-4"><b>PIN</b></div>
                                        <div class="col-sm-8">
                                            <p style="letter-spacing:10px" class="mb-0">{{ single_shuttle.pin }}</p>
                                        </div>
                                    </div> -->
                                    <div class="row mb-1">
                                        <div class="col-sm-4"><b>Added at</b></div>
                                        <div class="col-sm-8">{{ single_shuttle.added_at }}</div>
                                    </div>
                                </div>
                        
                                <div class="px-4 pb-3">
                                    <div class="row px-1">
                                        <div class="col-sm-6 px-2">
                                            <a href="{% url 'shuttles:edit-shuttle' single_shuttle.id %}">
                                                <button class="w-100 btn btn-primary" type="button">Edit</button>
                                            </a>
                                        </div>
                        
                                        <div class="col-sm-6 px-2">
                                            <a href="{% url 'shuttles:delete-shuttle' single_shuttle.id %}"
                                                    onclick="return confirm('Are you sure you want to delete this shuttle?')">
                                                <button class="w-100 btn btn-block btn-outline-danger" type="button">Delete</button>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                {% else %}

                    <div class="card-body p-2">
                        <div class="row" style="height: 550px;">
                            <div class="col-sm-12 py-5 my-5 d-flex align-items-center justify-content-center">
                                <div class="text-center">
                                    <img src="{% static 'notfound.png' %}" style="width: 150px; opacity: 0.6;" alt="">
                                    <div class="h4 fw-normal text-gray my-4" style="color: grey;">No shuttle selected</div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endif %}

        </div>
    </div>
</div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}